
project_id = "fvpbkkmnzlxbcxokxkce"

[api]
enabled = true

[db]
enabled = true

[studio]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
enabled = true

[functions.sync-employee-mappings]
verify_jwt = true
