// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvpbkkmnzlxbcxokxkce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cGJra21uemx4YmN4b2t4a2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTY1NDIsImV4cCI6MjA2MjIzMjU0Mn0.82Za5hPaRoR3kha2hwMF4pdAmPIYA79dCFwGDwnuaKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);